name: test

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Init Submodule
        run: git submodule update --init --recursive --depth 1

      - name: Setup Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: '3.11'

      - name: Pip install
        run: pip install -r requirements.txt

      - name: Download h2spec
        run: |
          wget https://github.com/summerwind/h2spec/releases/download/v2.6.0/h2spec_linux_amd64.tar.gz
          tar -xzf h2spec_linux_amd64.tar.gz

      - name: Export GitHub Actions cache environment variables
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: CMake config
        run: >
          cmake
          -Bbuild
          -DCMAKE_BUILD_TYPE=Release
          -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build build --target NewHttpImpl

      - name: Test
        run: |
          nohup ./build/NewHttpImpl &
          sleep 3
          ./h2spec -p 9956 -j test.xml
          pkill NewHttpImpl
        continue-on-error: true

      - name: Make report
        if: success() || failure()
        run: |
          mkdir public
          junit2html test.xml public/index.html

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v4
        if: success() || failure()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public