name: Ubuntu

on:
  push:
    branches:
      - main
      - stable
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  RELEASE_BUILD_TYPE: Release
  COVERAGE_BUILD_TYPE: Debug
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  test_release_job:
    runs-on: ubuntu-latest

    needs: test_coverage_job

    steps:
      - uses: actions/checkout@v3

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.RELEASE_BUILD_TYPE}} -DSESE_BUILD_TEST=ON -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.RELEASE_BUILD_TYPE}} -- -j4

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.RELEASE_BUILD_TYPE}} --extra-verbose

  test_coverage_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{github.workspace}}/build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_CXX_FLAGS="--coverage -fprofile-update=atomic" -DCMAKE_BUILD_TYPE=${{env.COVERAGE_BUILD_TYPE}} -DSESE_BUILD_TEST=ON -DCMAKE_TOOLCHAIN_FILE=/usr/local/share/vcpkg/scripts/buildsystems/vcpkg.cmake

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.COVERAGE_BUILD_TYPE}} -- -j4

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.COVERAGE_BUILD_TYPE}} --extra-verbose

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Dependencies(pip)
        run: pip install -r ${{github.workspace}}/scripts/requirements.txt

      - name: Coverage
        working-directory: ${{github.workspace}}
        run: python3 ${{github.workspace}}/scripts/make_coverage_report.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport
          path: ${{github.workspace}}/coverage