name: Ubuntu

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VCPKG_FEATURE_FLAGS: dependencygraph

jobs:
  test-with-release:
    runs-on: ubuntu-latest

    needs: test-with-coverage

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies(pip-ci)
        run: pip install -r ${{ github.workspace }}/ci/requirements.txt

      - name: Install Dependencies(pip-scripts)
        run: pip install -r ${{ github.workspace }}/scripts/requirements.txt

      - name: Check deps
        working-directory: ${{ github.workspace }}/build
        run: python3 -m ci.unix_check


      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-${{ hashFiles('**/vcpkg.json') }}

      - name: Configure CMake
        working-directory: ${{ github.workspace }}/build
        run: python3 -m ci.unix_config

      - name: Build
        working-directory: ${{ github.workspace }}/build
        run: python3 -m ci.unix_build

      - name: Test
        working-directory: ${{ github.workspace }}/build
        run: python3 -m ci.unix_test

  test-with-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies(pip-ci)
        run: pip install -r ${{ github.workspace }}/ci/requirements.txt

      - name: Install Dependencies(pip-scripts)
        run: pip install -r ${{ github.workspace }}/scripts/requirements.txt

      - name: Check deps
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_check

      - name: Cache Vcpkg Dependencies
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/build/vcpkg_installed
          key: ${{ runner.os }}-vcpkg-coverage-${{ hashFiles('**/vcpkg.json') }}

      - name: Configure CMake
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_config_coverage

      - name: Build
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_build_coverage

      - name: Test
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.unix_test_coverage

      - name: Coverage
        working-directory: ${{ github.workspace }}
        run: python3 -m ci.make_coverage_report

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CoverageReport
          path: ${{ github.workspace }}/coverage